# 项目相关配置
hujiang:
  # 名称
  name: Hujiang
  # 版本
  version: 3.1.0
  # 版权年份
  copyrightYear: 2018
  # 文件上传路径
  profile: profile/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口
  port: 8083
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# 用户配置
user:
  password:

    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  jmx:
    enabled: false
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  application:
    name: user-api
  # redis
  redis:
    host: 39.108.103.150
    port: 8083
    password: redis123
    # 缓存过期时间，单位毫秒
    ttime-to-live: 60000s
    spring.redis.lettuce.pool.max-idle: 50
    spring.redis.lettuce.pool.min-idle: 10
    spring.redis.lettuce.pool.max-active: 50
    spring.redis.lettuce.pool.max-wait: 10000

  activemq:
    user: admin
    password: admin
    broker-url: tcp://47.106.69.253:61616

    #true 表示使用内置的MQ，false则连接服务器
    in-memory: false
    pool:
      enabled: true #true表示使用连接池；false时，每发送一条数据创建一个连接
      max-connections: 10 #连接池最大连接数
      idle-timeout: 30000 #空闲的连接过期时间，默认为30秒
      #expiry-timeout: 0


eureka:
  instance:
    instance-id: user-api-8081
    prefer-ip-address: true # 访问路径可以显示 IP
      # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
       #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 2
#    ip-address: 120.79.129.65
    ip-address: localhost


  client:
    healthcheck:
      # 开启健康检查 （需要spring-boot-starter-actuator依赖）
      enabled: false
    serviceUrl:
      #     defaultZone: http://47.112.23.241:9001/eureka/,http://47.112.23.241:9002/eureka/  # 注册中心访问地址
     defaultZone: http://localhost:9003/eureka/  # 注册中心访问地址




# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.hujiang.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: hujiang
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.hujiang.project.zhgd
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
#  tablePrefix: sys_


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
feign:
  httpclient:
    connection-timeout: 60000
    #每条路由的最大连接数
    max-connections-per-route: 1000
    #最大连接
    max-connections: 3000
  hystrix:
    enabled: false